name: '1.0.0.$(Date:yyyyMMdd)$(Rev:r)'

variables:
- group: 'Common'
#- group: 'MyTemplate'

trigger:
  branches:
    include:
      - main
#  paths:
#    include:
#    - /core/*
#    exclude:
#    - /core/Tests/*
#    - /core/devops/*
#    - /core/Apps/*

resources:
  repositories:
  - repository: aertssenframework # identifier/alias
    type: git
    name: Aertssen.Framework

stages:
- stage: PackageProjects
  displayName: "Package Projects"
  dependsOn: []
  jobs:
        
  - job: Package_Portfolio
    displayName: 'Package Portfolio'
    pool:
      name: '$(Build.AzurePoolName)'
      vmImage: 'windows-latest'
    steps:  
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
        includeRootFolder: false 
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/portfolio.zip' 
        replaceExistingArchive: true 

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      condition: succeeded()
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)/portfolio.zip'
        ArtifactName: 'portfolio'